//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS.Model.NotificationResources", typeof(NotificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавил.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to назначил(-а).
        /// </summary>
        public static string Appointed {
            get {
                return ResourceManager.GetString("Appointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменил.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтвердил завершение.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалил.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to снял ответственность за.
        /// </summary>
        public static string Disappointed {
            get {
                return ResourceManager.GetString("Disappointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завершил.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавили.
        /// </summary>
        public static string HaveAdded {
            get {
                return ResourceManager.GetString("HaveAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to назначили.
        /// </summary>
        public static string HaveAppointed {
            get {
                return ResourceManager.GetString("HaveAppointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменили.
        /// </summary>
        public static string HaveChanged {
            get {
                return ResourceManager.GetString("HaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтвердили завершение.
        /// </summary>
        public static string HaveConfirmed {
            get {
                return ResourceManager.GetString("HaveConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалили.
        /// </summary>
        public static string HaveDeleted {
            get {
                return ResourceManager.GetString("HaveDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сняли ответственность за.
        /// </summary>
        public static string HaveDisappointed {
            get {
                return ResourceManager.GetString("HaveDisappointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to завершили.
        /// </summary>
        public static string HaveFinished {
            get {
                return ResourceManager.GetString("HaveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поместили.
        /// </summary>
        public static string HaveMoved {
            get {
                return ResourceManager.GetString("HaveMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to переместили в архив.
        /// </summary>
        public static string HaveMovedToArchive {
            get {
                return ResourceManager.GetString("HaveMovedToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отдали на проверку.
        /// </summary>
        public static string HaveMovedToChecking {
            get {
                return ResourceManager.GetString("HaveMovedToChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to переместили в запланированные.
        /// </summary>
        public static string HaveMovedToPlanned {
            get {
                return ResourceManager.GetString("HaveMovedToPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взяли на доработку.
        /// </summary>
        public static string HaveMovedToRebuild {
            get {
                return ResourceManager.GetString("HaveMovedToRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взяли в работу.
        /// </summary>
        public static string HaveTook {
            get {
                return ResourceManager.GetString("HaveTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поместил.
        /// </summary>
        public static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to переместил в архив.
        /// </summary>
        public static string MovedToArchive {
            get {
                return ResourceManager.GetString("MovedToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отдал на проверку.
        /// </summary>
        public static string MovedToChecking {
            get {
                return ResourceManager.GetString("MovedToChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to переместил в запланированные.
        /// </summary>
        public static string MovedToPlanned {
            get {
                return ResourceManager.GetString("MovedToPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поместил на доработку.
        /// </summary>
        public static string MovedToRebuild {
            get {
                return ResourceManager.GetString("MovedToRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string PartitionA {
            get {
                return ResourceManager.GetString("PartitionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздела.
        /// </summary>
        public static string PartitionG {
            get {
                return ResourceManager.GetString("PartitionG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string PartitionN {
            get {
                return ResourceManager.GetString("PartitionN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProjectA {
            get {
                return ResourceManager.GetString("ProjectA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекта.
        /// </summary>
        public static string ProjectG {
            get {
                return ResourceManager.GetString("ProjectG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProjectN {
            get {
                return ResourceManager.GetString("ProjectN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стадию.
        /// </summary>
        public static string StageA {
            get {
                return ResourceManager.GetString("StageA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стадии.
        /// </summary>
        public static string StageG {
            get {
                return ResourceManager.GetString("StageG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стадия.
        /// </summary>
        public static string StageN {
            get {
                return ResourceManager.GetString("StageN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачу.
        /// </summary>
        public static string TaskA {
            get {
                return ResourceManager.GetString("TaskA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string TaskG {
            get {
                return ResourceManager.GetString("TaskG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string TaskN {
            get {
                return ResourceManager.GetString("TaskN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на проверку.
        /// </summary>
        public static string ToChecking {
            get {
                return ResourceManager.GetString("ToChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взял в работу.
        /// </summary>
        public static string Took {
            get {
                return ResourceManager.GetString("Took", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на доработку.
        /// </summary>
        public static string ToRebuild {
            get {
                return ResourceManager.GetString("ToRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в работу.
        /// </summary>
        public static string ToWork {
            get {
                return ResourceManager.GetString("ToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
